### ISSUE TITLE
can not find db schema.

### ISSUE THREAD

**Issue by jcRwanda** [EzeibekweEmma/tech-school#1]
Hi Emma,

I wanted to express my gratitude for the incredible Tech-School repository. As someone who is new to Tailwind, I find it immensely helpful. However, I encountered an issue while trying to utilize this repository for reference. It seems that the database schema or the exported database files are missing. If it's possible for you to add them, it would be greatly appreciated. Thank you once again for your contribution.

Best regards, JC

**Comment by EzeibekweEmma** [comment]
Hi JC,
Go through the README under installation [no. 5 Set up your database - Schema](https://github.com/EzeibekweEmma/tech-school/blob/main/README.md#installation) you will find the schema.

**Comment by jcRwanda** [comment]
thanks a lot
